import { Tribunal } from './Tribunal';
import { OrgaoJulgador } from './OrgaoJulgador';
import { Magistrado } from './Magistrado';
import { TipoDeProcesso } from './TipoDeProcesso';
import { Tema } from './Tema';
import { JurisprudenciaTemaSubtema } from './JurisprudenciaTemaSubtema';
import { Cooperativa } from './Cooperativa';
import { SubTema } from './SubTema';
import { Ramo } from './Ramo';
import { Assunto } from './Assunto';

export class Jurisprudencia {
    id: number;
    dtDiarioJusticaEletronico: Date;
    numeracao: string;
    razaoSocialCooperativa: string;
    txUrlJurisprudencia: string;
    decisao: string;
    dtInclusaoSistema: Date;
    dtAlteracaoSistema: Date;
    tipoMovimentacao: string;
    tipoDecisao: string;
    compendio: boolean;
    informativo: boolean;
    rrc: string;
    classificacao: string;
    registroAnterior: Jurisprudencia;
    tribunal: Tribunal;
    orgaoJulgador: OrgaoJulgador;
    magistrado: Magistrado;
    numeracaoRepetitiva: string;
    seqCooperativa: number;
    seqRamo: number;
    jurisprudenciaTemaSubtemas: Array<JurisprudenciaTemaSubtema>;
    tipoProcesso: TipoDeProcesso;
    temas: Array<Tema>;
    subTemas: Array<SubTema>;
    anexo: string;
    cooperativa: Cooperativa;
    identificacao: string;
    ramo: Ramo;
    assunto: Assunto;
}
